name: Feature Request
description: Sugerir uma nova funcionalidade ou melhoria
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / motivação
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solução proposta
    validations:
      required: false
